loadtest:
  users: 10
  cooldown: 5 # indicates the cooldown period for a user to send a new request
  rampup: 2 # indicates the ramp-up period for creating new users.
  totalTime: 60 # indicates the total time of the load test run
  iterations: 5 # total iteration count of use cases for each user.